server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crudusers
    username: root
    password: root
  jpa:
    properties:
      hibernate:
       # dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update